### ISSUE TITLE
Davis, KIBA, DTC, Metz, and ToxCast

### ISSUE THREAD

**Issue by speakstone** [vtarasv/3d-prot-dta#4]
Regarding the Davis, KIBA, DTC, Metz, and ToxCast datasets, could you please guide me to where I can find the prediction results using AlphaFold? I have delved deeply into your work and understand its immense value for drug discovery. Compared to the current cutting-edge algorithms, yours stands out as the most significant. As a newcomer to the research field, I sincerely hope for your guidance and response to my queries.

**Comment by vtarasv** [comment]
The KIBA dataset is annotated directly by the UniProt IDs and the corresponding structures may be found in the [AlphaFold2 database](https://alphafold.ebi.ac.uk/download).

The Davis dataset proteins are annotated by the gene names and can be mapped to the UniProt identifiers by the [UniProt mapping tool ](https://www.uniprot.org/id-mapping). The Davis data, however, includes proteins with mutations. Thus, the structures have to be predicted manually. The useful tool for the AlphaFold custom sequence prediction is [ColabFold](https://github.com/sokrypton/ColabFold).

You can also find prepared 3D structures in this repository's [data folder](https://github.com/vtarasv/3d-prot-dta/tree/800bdeabf5bc4c12f02f6d323050ac29644dd315/data) for both abovementioned datasets. 

I didn't work with the DTC, Metz, and ToxCast datasets. Therefore, I cannot give direct guidance regarding them.

**Comment by speakstone** [comment]
> The KIBA dataset is annotated directly by the UniProt IDs and the corresponding structures may be found in the [AlphaFold2 database](https://alphafold.ebi.ac.uk/download).
> 
> The Davis dataset proteins are annotated by the gene names and can be mapped to the UniProt identifiers by the [UniProt mapping tool ](https://www.uniprot.org/id-mapping). The Davis data, however, includes proteins with mutations. Thus, the structures have to be predicted manually. The useful tool for the AlphaFold custom sequence prediction is [ColabFold](https://github.com/sokrypton/ColabFold).
> 
> You can also find prepared 3D structures in this repository's [data folder](https://github.com/vtarasv/3d-prot-dta/tree/800bdeabf5bc4c12f02f6d323050ac29644dd315/data) for both abovementioned datasets.
> 
> I didn't work with the DTC, Metz, and ToxCast datasets. Therefore, I cannot give direct guidance regarding them.

Thank you very much for your response. As you mentioned, I have found AlphaFold results for all entries in the KIBA dataset, except for P78527. Unfortunately, there seems to be a significant amount of missing data from the DAVIS dataset. I truly admire and appreciate the work you've done in this area; your research has added immense value to the field. I noticed that you have reconstructed all datasets and obtained the AlphaFold2 predictions before processing them with Uniprot. Have you considered open-sourcing this data? It would be of tremendous help to researchers with limited resources.

**Comment by vtarasv** [comment]
Sure, as I mentioned above, the data can be found [here ](https://github.com/vtarasv/3d-prot-dta/tree/800bdeabf5bc4c12f02f6d323050ac29644dd315/data): [prot_3d_for_Davis.tar.gz](https://github.com/vtarasv/3d-prot-dta/blob/800bdeabf5bc4c12f02f6d323050ac29644dd315/data/prot_3d_for_Davis.tar.gz), [prot_3d_for_KIBA.tar.gz](https://github.com/vtarasv/3d-prot-dta/blob/800bdeabf5bc4c12f02f6d323050ac29644dd315/data/prot_3d_for_KIBA.tar.gz)

**Comment by speakstone** [comment]
> [当然，正如我上面提到的，可以在这里](https://github.com/vtarasv/3d-prot-dta/tree/800bdeabf5bc4c12f02f6d323050ac29644dd315/data)找到数据：[prot_3d_for_Davis.tar.gz](https://github.com/vtarasv/3d-prot-dta/blob/800bdeabf5bc4c12f02f6d323050ac29644dd315/data/prot_3d_for_Davis.tar.gz)、[prot_3d_for_KIBA.tar.gz](https://github.com/vtarasv/3d-prot-dta/blob/800bdeabf5bc4c12f02f6d323050ac29644dd315/data/prot_3d_for_KIBA.tar.gz)

I apologize for any confusion in my previous message. From what I've gathered, the provided PDB data has been processed through Uniprot. Would it be possible for you to share the original PDB data?

**Comment by speakstone** [comment]
> Sure, as I mentioned above, the data can be found [here ](https://github.com/vtarasv/3d-prot-dta/tree/800bdeabf5bc4c12f02f6d323050ac29644dd315/data): [prot_3d_for_Davis.tar.gz](https://github.com/vtarasv/3d-prot-dta/blob/800bdeabf5bc4c12f02f6d323050ac29644dd315/data/prot_3d_for_Davis.tar.gz), [prot_3d_for_KIBA.tar.gz](https://github.com/vtarasv/3d-prot-dta/blob/800bdeabf5bc4c12f02f6d323050ac29644dd315/data/prot_3d_for_KIBA.tar.gz)

I apologize for any confusion in my previous message. From what I've gathered, the provided PDB data has been processed through Uniprot. Would it be possible for you to share the original PDB data?
